swagger: '2.0'
info:
  title: Example yaml.spec
  description: This is an example text **HELLO FROM MARKDOWN**
  termsOfService: javascript:alert(document.cookie)
  contact: 
    name: API Support,
    url: javascript:alert(document.cookie),
    email: javascript:alert(document.cookie)
paths:
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
